### PR TITLE
Falcons velocitycontrol -- implementation

### PR DESCRIPTION
**Pull request by janfeitsma**
Implementation.

This branch has gotten way too big. Let's integrate, Jurge can you approve? I shall try to cut it up next time :)...

Status: Simulation on Falcons SW stack OK. (Branch: `bazel/MRA_prototype_vc_with_csfix`)

Bonus: see component TrajectoryGeneration and its plots.

Remaining items:
- [x] integrate in Falcons code
- [x] careful with change in RCS definition ... can of worms has been eaten ...
- [x] test in simulator
- [x] implement STOP/watchdog

Note: coordinate systems are now according to MSL spec (Falcons was using a 90-degree rotated RCS w.r.t. FCS).

### CODE REVIEW

**Comment by jveijck** [comment]
CMakeLists.txt needs a update.
On line 47 libraries/geometry/geometry.cpp is mentioned. This file does not exists.
Should the following files not be added:
	libraries/geometry/clipping.cpp
	libraries/geometry/pose.cpp
	libraries/geometry/position.cpp
	libraries/geometry/test-pose.cpp
	libraries/geometry/test-position.cpp
	libraries/geometry/velocity.cpp

**Comment by janfeitsma** [comment]
Yeah I did not bother with cmake yet, I am still testing and integrating in Falcons code (under the bazel integration stream), it has become quite a can of worms because our FCS/RCS definitions were 90 degrees off and it had impact at many places, sometimes tricky...

Anyway I really could use some help on the cmake front. Edit: see #4.
Then I can keep focusing on content and framework (codegen for instance).

**Comment by janfeitsma** [comment]
Jurge, I'd like to integrate this branch into main now that simulation at Falcons is OK-ish. Please comment.

(Somehow I cannot invite you to review, maybe some permission issue?)

**Comment by jveijck** [comment]
> 

I agree. If branch works in simulation, then it is ok for moving it to the main branch.

**Pull request merged**
